// full-file: src/index.js
const fs = require('fs');
const path = require('path');
const { fetchJob } = require('./playwright');
const { matchKeywords } = require('./keywords');
const { commitOutbox } = require('./git-helper');
const { sendTelegram } = require('./telegram');

const JOBS_FILE = path.resolve('jobs.txt');
const RESUME_FILE = path.resolve('master_resume.json');
const OUTBOX_DIR = path.resolve('outbox');

async function main() {
  if (!fs.existsSync(JOBS_FILE)) {
    console.error('jobs.txt not found');
    process.exit(1);
  }
  if (!fs.existsSync(RESUME_FILE)) {
    console.error('master_resume.json not found');
    process.exit(1);
  }
  if (!fs.existsSync(OUTBOX_DIR)) fs.mkdirSync(OUTBOX_DIR);

  const jobs = fs.readFileSync(JOBS_FILE, 'utf8')
    .split(/\r?\n/)
    .map(s => s.trim())
    .filter(Boolean);

  const resume = JSON.parse(fs.readFileSync(RESUME_FILE, 'utf8'));

  for (const url of jobs) {
    console.log('Processing', url);
    try {
      const job = await fetchJob(url);
      console.log('Fetched:', job.title || '(no title)');

      const match = matchKeywords(job.description || '', resume);

      const slug = (job.title || 'job').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g,'').slice(0,60);
      const filename = `${slug || 'job'}-${Date.now()}.md`;
      const filepath = path.join(OUTBOX_DIR, filename);

      const md = buildMarkdown(job, match, resume, url);
      fs.writeFileSync(filepath, md, 'utf8');
      console.log('Wrote', filepath);

      // commit to outbox branch & push
      await commitOutbox(filepath);

      // Telegram notification with link to outbox file
      const repo = process.env.GITHUB_REPOSITORY || '<your-repo>';
      const fileUrl = `https://github.com/${repo}/blob/outbox/${encodeURIComponent(filename)}`;
      await sendTelegram(`✅ Job processed: *${job.title || 'Job'}*\nCompany: ${job.company || 'N/A'}\nMatch score: ${match.score}\nDraft: ${fileUrl}`);

    } catch (err) {
      console.error('Error processing', url, err);
      await sendTelegram(`⚠️ JobBot error processing ${url}\n${err.message || err}`);
    }
  }
  console.log('Done.');
  process.exit(0);
}

function buildMarkdown(job, match, resume, url) {
  const lines = [];
  lines.push(`# ${job.title || 'Job'}\n`);
  lines.push(`**Company:** ${job.company || 'N/A'}`);
  lines.push(`**URL:** ${url}`);
  lines.push(`\n## Extracted description\n`);
  lines.push(job.description ? `\`\`\`\n${job.description}\n\`\`\`` : '_No description found_');
  lines.push('\n## Match summary\n');
  lines.push(`- match score: ${match.score}`);
  lines.push(`- matched skills: ${match.matched.join(', ') || 'None'}`);
  lines.push(`- partial matches: ${match.partial.join(', ') || 'None'}`);
  lines.push(`- missing skills: ${match.missing.join(', ') || 'None'}`);
  lines.push('\n## Suggested bullets (from resume)\n');
  for (const b of match.matchedBullets) {
    lines.push(`- ${b}`);
  }
  lines.push('\n---\n*Generated by JobBot*');
  return lines.join('\n');
}

main();
